# See config.example.yml for documentation.
object_base: orig/GQ4E78
object: sys/main.dol
hash: 98b3564318f804c1fae7291e8ba1a80fc14dc9d6
symbols: config/GQ4E78/symbols.txt
splits: config/GQ4E78/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 11
